name: Update constraints-dev.txt
'on':
  schedule:
  - cron: 0 3 * * 1
  workflow_dispatch: null
jobs:
  update-constraints:
    if: github.repository_owner == 'z1fkoisp'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Checkout "update-constraints" in-house CI action
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: instructlab/ci-actions
        path: ci-actions
        ref: 88641ccaf122964eacdc1a82b18bda369b6f99bd
        sparse-checkout: 'actions/update-constraints

          '
    - name: Update constraints
      id: update-constraints
      uses: ./ci-actions/actions/update-constraints
      with:
        gh-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
